# Aplication of AI:
    - Speech recognation
    - NLP
    - Image recognation

In [1]:
# ML
Provides computers with the ability to learn without being explicitly programmed




SyntaxError: invalid syntax (<ipython-input-1-a656169b3596>, line 2)

### Limitation of mL
    - 

In [3]:
# Make a vector in numpy
import numpy as np


v = np.array([5, 2, 1])

print(v)

print(v.shape)

[5 2 1]
(3,)


In [4]:
v[1]

2

In [8]:
v.shape


(3,)

In [9]:
v = np.array([[5, 2, 1]])

# print(v)

print(v.shape)

[[5 2 1]]
(1, 3)


In [11]:
v_t = np.transpose(v)
print(v_t)
v_t.shape # (3, 1) = (row, column)

[[5]
 [2]
 [1]]


(3, 1)

In [12]:
v[0]

array([5, 2, 1])

In [13]:
v[0][1]

2

In [14]:
# in DS-2.2 our input should 2d array

In [15]:
# Make a matrix

matrix = np.array([[1,2,3], [2, 0, 1]])

print(matrix)

print(matrix.shape)

print(matrix.size) # size is number of elements

[[1 2 3]
 [2 0 1]]
(2, 3)
3


In [16]:
matrix_t = np.transpose(matrix)
print(matrix_t)

print(matrix_t.shape)

print(matrix_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


In [20]:
# Arrange or reshape the matrix (2D array or 2D Tensor)

v_2 = np.array([[1,2,3], [2, 0, 1]])

print("just a reshape like transpose: ",v_2.reshape(3, 2))

# By applying the following reshape we transform the amtrix into 3D Tenosor

print("Specified 1st parameter: ",v_2.reshape(3, 1, 2))
print("UNSpecified 1st parameter: ", v_2.reshape(-1, 1, 2))

just a reshape like transpose:  [[1 2]
 [3 2]
 [0 1]]
Specified 1st parameter:  [[[1 2]]

 [[3 2]]

 [[0 1]]]
Specified 1st parameter:  [[[1 2]]

 [[3 2]]

 [[0 1]]]


In [21]:
# Make a 3D Tensor in numpy
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
(2, 2, 3)


In [22]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
print(v[1])

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [26]:
# print(v[2]) this gives error because we have only 2 depth

In [27]:
print(v.size) # 12

12


In [28]:
print(v.reshape(3, 2, -1)) # this equals to v.reshape(3, 2, 2)

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [31]:
print(v.reshape(3, 1, -1))

[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 11. 12. 13.]]]


In [41]:
print(v.reshape(3, -1, 1)) # we want one column and '-1' is '4' here which is the num of rows

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [11.]
  [12.]
  [13.]]]


In [42]:
# Make a 4D Tensor Matrix

v_4 = np.zeros((2, 3, 5, 5))

In [45]:
print(v_4)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [48]:
# Make 5D Tensor in numpy
v_5 = np.zeros((2, 2, 3, 5, 5)) # 2 by 2 and depth is 3 and the 5 by 5
print(v_5)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 